# Generated by Django 3.2.12 on 2022-03-21 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faq', '0005_faqitem_update_default_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='faqitem',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
