services:
  rustfs:
    image: rustfs/rustfs
    container_name: collecte-s3
    ports:
      - target: 9000
        published: 9000
      - target: 9001
        published: 9001
    environment:
      - RUSTFS_VOLUMES=/data/rustfs
      - RUSTFS_ADDRESS=0.0.0.0:9000
      - RUSTFS_CONSOLE_ADDRESS=0.0.0.0:9001
      - RUSTFS_CONSOLE_ENABLE=true
      - RUSTFS_CONSOLE_CORS_ALLOWED_ORIGINS=*
      - RUSTFS_ACCESS_KEY=admin # CHANGEME
      - RUSTFS_SECRET_KEY=admin # CHANGEME
      - RUSTFS_OBS_LOGGER_LEVEL=info
    volumes:
      - type: volume
        source: rustfs_data
        target: /data
      - type: volume
        source: rustfs_logs
        target: /logs
  postgres:
    image: postgres:15.15-alpine
    container_name: collecte-db
    ports:
      - target: 5432
        published: 5432
    environment:
      POSTGRES_DB: ecc
      POSTGRES_USER: ecc
      POSTGRES_PASSWORD: ecc
    volumes:
      - type: volume
        source: postgres_data
        target: /var/lib/postgresql/data
    command: ["postgres", "-c", "log_statement=all", "-c", "max_connections=100"]

volumes:
  rustfs_data:
  rustfs_logs:
  postgres_data:
