# Generated by Django 2.2.22 on 2021-10-18 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parametre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, editable=False, verbose_name='order')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('code', models.CharField(max_length=255, verbose_name='code')),
                ('nom', models.CharField(max_length=255, verbose_name='nom')),
                ('url', models.CharField(max_length=255, verbose_name='url')),
                ('ordre', models.PositiveIntegerField(verbose_name='ordre')),
            ],
            options={
                'verbose_name': 'Paramètre',
                'verbose_name_plural': 'Paramètres',
                'ordering': ('order',),
            },
        ),
    ]
