# Generated by Django 2.2.22 on 2021-10-19 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametres', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='parametre',
            name='title',
            field=models.CharField(default='title', max_length=255, verbose_name='title'),
            preserve_default=False,
        ),
    ]
