# Generated by Django 2.2.22 on 2021-10-22 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametres', '0002_parametre_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parametre',
            name='nom',
            field=models.CharField(max_length=255, null=True, verbose_name='nom'),
        ),
        migrations.AlterField(
            model_name='parametre',
            name='ordre',
            field=models.PositiveIntegerField(null=True, verbose_name='ordre'),
        ),
        migrations.AlterField(
            model_name='parametre',
            name='title',
            field=models.CharField(max_length=255, null=True, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='parametre',
            name='url',
            field=models.CharField(max_length=255, null=True, verbose_name='url'),
        ),
    ]
