# Generated by Django 2.2.22 on 2021-10-25 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parametres', '0003_auto_20211022_1129'),
    ]

    operations = [
        migrations.RunSQL("insert into auth_group_permissions values (nextval('auth_group_permissions_id_seq'), (select id from auth_group where name = 'admin_metier'), (select id from auth_permission where codename = 'add_parametre'));"),
        migrations.RunSQL("insert into auth_group_permissions values (nextval('auth_group_permissions_id_seq'), (select id from auth_group where name = 'admin_metier'), (select id from auth_permission where codename = 'change_parametre'));"),
        migrations.RunSQL("insert into auth_group_permissions values (nextval('auth_group_permissions_id_seq'), (select id from auth_group where name = 'admin_metier'), (select id from auth_permission where codename = 'delete_parametre'));"),
        migrations.RunSQL("insert into auth_group_permissions values (nextval('auth_group_permissions_id_seq'), (select id from auth_group where name = 'admin_metier'), (select id from auth_permission where codename = 'view_parametre'));"),
    ]
