# Generated by Django 2.2.22 on 2021-10-25 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametres', '0005_auto_20211025_1425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parametre',
            name='code',
            field=models.CharField(help_text='LIEN_FOOTER, LOGO_FOOTER, ou ENTITY_PICTURE', max_length=255, verbose_name='code'),
        ),
        migrations.AlterField(
            model_name='parametre',
            name='name',
            field=models.CharField(help_text="Texte affiché pour les paramètres de type 'lien' et texte alternatif pour les paramètres de type 'image'", max_length=255, null=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='parametre',
            name='title',
            field=models.CharField(help_text="attribut 'title' des paramètres de type 'lien'", max_length=255, null=True, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='parametre',
            name='url',
            field=models.CharField(help_text="url de destination pour les paramètres de type 'lien' et url de l'image pour les paramètres de type 'image'", max_length=255, null=True, verbose_name='url'),
        ),
    ]
