# Generated by Django 3.2.12 on 2022-03-21 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametres', '0005_auto_20211025_1434'),
    ]

    operations = [
        migrations.AddField(
            model_name='parametre',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
