# Generated by Django 3.2.15 on 2022-09-06 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(help_text='Message affiché sur la page de connexion', max_length=255, verbose_name='texte')),
                ('start_date', models.DateTimeField(blank=True, help_text="Heure d'affichage de l'alerte", null=True, verbose_name="heure d'affichage")),
                ('end_date', models.DateTimeField(blank=True, help_text="Heure de fin d'affichage de l'alerte", null=True, verbose_name="heure d'échéance")),
            ],
            options={
                'verbose_name': 'Alerte',
                'verbose_name_plural': 'Alertes',
                'ordering': ('start_date',),
            },
        ),
    ]
