# Generated by Django 2.2.22 on 2021-10-15 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecc', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL("insert into auth_group_permissions values (nextval('auth_group_permissions_id_seq'), (select id from auth_group where name = 'admin_metier'), (select id from auth_permission where codename = 'change_site'));"),
    ]
