# Generated by Django 2.2.22 on 2021-10-15 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecc', '0002_update_permissions'),
    ]

    operations = [
        migrations.RunSQL("insert into auth_group_permissions values (nextval('auth_group_permissions_id_seq'), (select id from auth_group where name = 'admin_metier'), (select id from auth_permission where codename = 'add_crontabschedule'));"),
        migrations.RunSQL("insert into auth_group_permissions values (nextval('auth_group_permissions_id_seq'), (select id from auth_group where name = 'admin_metier'), (select id from auth_permission where codename = 'change_crontabschedule'));"),
        migrations.RunSQL("insert into auth_group_permissions values (nextval('auth_group_permissions_id_seq'), (select id from auth_group where name = 'admin_metier'), (select id from auth_permission where codename = 'delete_crontabschedule'));"),
        migrations.RunSQL("insert into auth_group_permissions values (nextval('auth_group_permissions_id_seq'), (select id from auth_group where name = 'admin_metier'), (select id from auth_permission where codename = 'view_crontabschedule'));"),
        migrations.RunSQL("insert into auth_group_permissions values (nextval('auth_group_permissions_id_seq'), (select id from auth_group where name = 'admin_metier'), (select id from auth_permission where codename = 'add_intervalschedule'));"),
        migrations.RunSQL("insert into auth_group_permissions values (nextval('auth_group_permissions_id_seq'), (select id from auth_group where name = 'admin_metier'), (select id from auth_permission where codename = 'change_intervalschedule'));"),
        migrations.RunSQL("insert into auth_group_permissions values (nextval('auth_group_permissions_id_seq'), (select id from auth_group where name = 'admin_metier'), (select id from auth_permission where codename = 'delete_intervalschedule'));"),
        migrations.RunSQL("insert into auth_group_permissions values (nextval('auth_group_permissions_id_seq'), (select id from auth_group where name = 'admin_metier'), (select id from auth_permission where codename = 'view_intervalschedule'));"),
        migrations.RunSQL("insert into auth_group_permissions values (nextval('auth_group_permissions_id_seq'), (select id from auth_group where name = 'admin_metier'), (select id from auth_permission where codename = 'add_periodictask'));"),
        migrations.RunSQL("insert into auth_group_permissions values (nextval('auth_group_permissions_id_seq'), (select id from auth_group where name = 'admin_metier'), (select id from auth_permission where codename = 'change_periodictask'));"),
        migrations.RunSQL("insert into auth_group_permissions values (nextval('auth_group_permissions_id_seq'), (select id from auth_group where name = 'admin_metier'), (select id from auth_permission where codename = 'delete_periodictask'));"),
        migrations.RunSQL("insert into auth_group_permissions values (nextval('auth_group_permissions_id_seq'), (select id from auth_group where name = 'admin_metier'), (select id from auth_permission where codename = 'view_periodictask'));"),
        migrations.RunSQL("insert into auth_group_permissions values (nextval('auth_group_permissions_id_seq'), (select id from auth_group where name = 'admin_metier'), (select id from auth_permission where codename = 'add_periodictasks'));"),
        migrations.RunSQL("insert into auth_group_permissions values (nextval('auth_group_permissions_id_seq'), (select id from auth_group where name = 'admin_metier'), (select id from auth_permission where codename = 'change_periodictasks'));"),
        migrations.RunSQL("insert into auth_group_permissions values (nextval('auth_group_permissions_id_seq'), (select id from auth_group where name = 'admin_metier'), (select id from auth_permission where codename = 'delete_periodictasks'));"),
        migrations.RunSQL("insert into auth_group_permissions values (nextval('auth_group_permissions_id_seq'), (select id from auth_group where name = 'admin_metier'), (select id from auth_permission where codename = 'view_periodictasks'));"),
        migrations.RunSQL("insert into auth_group_permissions values (nextval('auth_group_permissions_id_seq'), (select id from auth_group where name = 'admin_metier'), (select id from auth_permission where codename = 'add_solarschedule'));"),
        migrations.RunSQL("insert into auth_group_permissions values (nextval('auth_group_permissions_id_seq'), (select id from auth_group where name = 'admin_metier'), (select id from auth_permission where codename = 'change_solarschedule'));"),
        migrations.RunSQL("insert into auth_group_permissions values (nextval('auth_group_permissions_id_seq'), (select id from auth_group where name = 'admin_metier'), (select id from auth_permission where codename = 'delete_solarschedule'));"),
        migrations.RunSQL("insert into auth_group_permissions values (nextval('auth_group_permissions_id_seq'), (select id from auth_group where name = 'admin_metier'), (select id from auth_permission where codename = 'view_solarschedule'));"),
        migrations.RunSQL("insert into auth_group_permissions values (nextval('auth_group_permissions_id_seq'), (select id from auth_group where name = 'admin_metier'), (select id from auth_permission where codename = 'add_clockedschedule'));"),
        migrations.RunSQL("insert into auth_group_permissions values (nextval('auth_group_permissions_id_seq'), (select id from auth_group where name = 'admin_metier'), (select id from auth_permission where codename = 'change_clockedschedule'));"),
        migrations.RunSQL("insert into auth_group_permissions values (nextval('auth_group_permissions_id_seq'), (select id from auth_group where name = 'admin_metier'), (select id from auth_permission where codename = 'delete_clockedschedule'));"),
        migrations.RunSQL("insert into auth_group_permissions values (nextval('auth_group_permissions_id_seq'), (select id from auth_group where name = 'admin_metier'), (select id from auth_permission where codename = 'view_clockedschedule'));"),
    ]
