# Generated by Django 2.2.22 on 2021-10-18 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profiles', '0016_auto_20210730_1614'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'Profil Utilisateur', 'verbose_name_plural': 'Profils Utilisateurs'},
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profile_type',
            field=models.CharField(choices=[('audited', 'Organisme interrogé'), ('inspector', 'Demandeur')], max_length=255),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='send_files_report',
            field=models.BooleanField(default=False, help_text='Envoyer par email le rapport des fichiers uplodés ?', verbose_name='Envoi Rapport de Fichiers'),
        ),
    ]
