# Generated by Django 2.2.22 on 2021-10-18 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profiles', '0017_auto_20211018_1325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='controls',
            field=models.ManyToManyField(blank=True, related_name='user_profiles', to='control.Control', verbose_name='procédures'),
        ),
    ]
