# Generated by Django 3.2.13 on 2022-07-04 09:06

from django.db import migrations


def set_default_send_files_report(apps, schema_editor):
    UserProfile = apps.get_model('user_profiles', 'UserProfile')
    for profile in UserProfile.objects.filter(send_files_report=False):
        profile.send_files_report = True
        profile.save()


class Migration(migrations.Migration):

    dependencies = [
        ('user_profiles', '0020_alter_userprofile_send_files_report'),
    ]

    operations = [
        migrations.RunPython(set_default_send_files_report),
    ]
