# Generated by Django 3.2.16 on 2022-11-15 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0051_alter_responsefile_file'),
        ('user_profiles', '0021_default_send_files_report'),
    ]

    operations = [
        migrations.CreateModel(
            name='Access',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_type', models.CharField(choices=[('repondant', 'Répondant'), ('demandeur', 'Demandeur')], max_length=255)),
                ('control', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='access', to='control.control')),
                ('userprofile', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='access', to='user_profiles.userprofile', verbose_name='userprofile')),
            ],
            options={
                'verbose_name': 'Accès à un contrôle',
                'verbose_name_plural': 'Accès des utilisateurs aux contrôles',
            },
        ),
    ]
