# Generated by Django 3.2.16 on 2022-11-15 10:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0051_alter_responsefile_file'),
        ('user_profiles', '0022_access'),
    ]

    operations = [
        migrations.AlterField(
            model_name='access',
            name='control',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='access', to='control.control'),
        ),
        migrations.AlterField(
            model_name='access',
            name='userprofile',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='access', to='user_profiles.userprofile', verbose_name='userprofile'),
        ),
    ]
