# Generated by Django 3.2.13 on 2022-07-04 09:06

from django.db import migrations

class Migration(migrations.Migration):

    dependencies = [
        ('user_profiles', '0024_add_access_field_userprofile_controls'),
    ]

    operations = [
        migrations.RunSQL("SELECT setval('user_profiles_access_id_seq', (SELECT MAX(id) FROM user_profiles_access))"),
    ]
