# Generated by Django 3.2.16 on 2022-12-06 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profiles', '0025_update_access_sequence'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='access',
            options={'verbose_name': "Accès d'un utilisateur à un contrôle", 'verbose_name_plural': 'Accès des utilisateurs à des contrôles'},
        ),
    ]
