# Generated by Django 3.2.17 on 2025-09-10 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profiles', '0027_remove_userprofile_controls'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrphanUserPurgeHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('username', models.CharField(blank=True, max_length=255, null=True)),
                ('profile_type', models.CharField(blank=True, max_length=255, null=True)),
                ('date_joined', models.DateTimeField(blank=True, null=True)),
                ('is_physically_deleted', models.BooleanField(default=False)),
                ('physical_deletion_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'purge_histo_rep_orphelins',
            },
        ),
    ]
