# Generated by Django 3.2.17 on 2025-09-12 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profiles', '0028_orphanuserpurgehistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurgeEligibleRepOrphTrv',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('username', models.CharField(blank=True, max_length=255, null=True)),
                ('profile_type', models.CharField(blank=True, max_length=255, null=True)),
                ('date_joined', models.DateTimeField(blank=True, null=True)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=255, null=True)),
                ('id_control_associe', models.CharField(blank=True, max_length=255, null=True)),
                ('date_extraction', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'purge_eligible_rep_orph_trv',
            },
        ),
    ]
