# Generated by Django 2.2.22 on 2021-09-13 13:52

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TOS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('description', ckeditor.fields.RichTextField(blank=True, verbose_name='description')),
            ],
            options={
                'verbose_name': "Conditions Générales d'Utilisation",
                'verbose_name_plural': "Conditions Générales d'Utilisation",
            },
        ),
    ]
