# Generated by Django 3.2.12 on 2022-03-21 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tos', '0002_auto_20210913_1618'),
    ]

    operations = [
        migrations.AddField(
            model_name='cguitem',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
