# Generated by Django 2.2.22 on 2021-10-18 13:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0041_auto_20200424_1047'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='control',
            options={'verbose_name': 'Procédure', 'verbose_name_plural': 'Procédures'},
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='control',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questionnaires', to='control.Control', verbose_name='procédure'),
        ),
    ]
