# Generated by Django 3.2.7 on 2022-02-07 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0044_questionnaire_is_finalized'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionnaire',
            name='is_replied',
            field=models.BooleanField(default=False, help_text="Ce questionnaire a-t-il obtenu toutes les réponses de l'organisme répondant ?", verbose_name='répondu'),
        ),
    ]
