# Generated by Django 3.2.12 on 2022-03-21 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0046_alter_questionnaire_control'),
    ]

    operations = [
        migrations.AddField(
            model_name='control',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
