# Generated by Django 3.2.12 on 2022-03-28 08:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0047_control_is_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionnaire',
            name='control',
            field=models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questionnaires', to='control.control', verbose_name='procédure'),
        ),
    ]
