# Generated by Django 3.2.13 on 2022-06-28 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0048_alter_questionnaire_control'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionnaire',
            name='sent_date',
            field=models.DateField(blank=True, help_text='Date de transmission du questionnaire', null=True, verbose_name="date d'envoi"),
        ),
        migrations.AlterField(
            model_name='responsefile',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='Ce fichier est-il dans la corbeille ?', verbose_name='Supprimé'),
        ),
    ]
