# Generated by Django 3.2.14 on 2022-07-11 13:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0049_auto_20220628_0938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='control',
            name='reference_code',
            field=models.CharField(error_messages={'unique': 'UNIQUE'}, help_text='Ce code est utilisé notamment pour le dossier de stockage des réponses', max_length=30, unique=True, validators=[django.core.validators.RegexValidator(message='INVALID', regex='^[\\.\\s\\w-]+$')], verbose_name='code de référence'),
        ),
    ]
