# Generated by Django 3.2.16 on 2022-12-20 16:34

import control.models
import control.upload_path
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0051_alter_responsefile_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionnaireFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, editable=False, verbose_name='order')),
                ('file', models.FileField(upload_to=control.upload_path.questionnaire_file_path, verbose_name='fichier')),
                ('questionnaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questionnaire_files', to='control.questionnaire', verbose_name='questionnaire')),
            ],
            options={
                'verbose_name': 'Questionnaire: Fichier Annexe',
                'verbose_name_plural': 'Questionnaire: Fichiers Annexes',
                'ordering': ('questionnaire', 'order'),
            },
            bases=(models.Model, control.models.FileInfoMixin),
        ),
    ]
