# Generated by Django 3.2.16 on 2022-12-21 16:56

import control.upload_path
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0052_questionnairefile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionnairefile',
            name='file',
            field=models.FileField(upload_to=control.upload_path.questionnaire_pj_file_path, verbose_name='fichier'),
        ),
    ]
