# Generated by Django 4.2.1 on 2025-03-25 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0055_control_is_pinned'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurgeEligibleControlTrv',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('control_id', models.IntegerField()),
            ],
            options={
                'db_table': 'purge_eligible_control_trv',
            },
        ),
        migrations.CreateModel(
            name='PurgeHistoControl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('control_id', models.IntegerField()),
                ('reference_code', models.CharField(max_length=30)),
                ('is_supp_logique', models.BooleanField(default=False)),
                ('date_supp_logique', models.DateTimeField(blank=True, null=True)),
                ('is_supp_physique', models.BooleanField(default=False)),
                ('date_supp_physique', models.DateTimeField(blank=True, null=True)),
                ('code_ano', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'purge_histo_control',
            },
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='last_response_file_action',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
