# Generated by Django 4.2.1 on 2025-07-01 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0056_purgeeligiblecontroltrv_purgehistocontrol_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='control',
            name='created_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date de création'),
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='created_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date de création'),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='last_response_file_action',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date de dernière modification'),
        ),
    ]
